### ISSUE TITLE
Process is stuck when running sdk on Linux

### ISSUE THREAD

**Issue by IliaMarek** [Insta360Develop/MediaSDK-Cpp#52]
**Issue description:**

I am trying to run the MediaSDK (3.0.1.2) on docker (ubuntu:22.04).
The machine does not have any Nvidia GPU, so I am using the -disable_cuda option.

The command I am running:
`xvfb-run MediaSDKTest -inputs "input file" -output "output file" -disable_cuda`

**The output:**
```
start stitch 
libevent use phreads:0
[07-06 17:32:43.445]  4208 4208 E ins_load_cuda_context.cc:0062:  err:100 Could not initialize the CUDA driver API
progress: 0; finished: 0
[07-06 17:32:43.495]  4208 4242 E ffmpeg:0000:  AVHWDeviceContext @ 0x777d4c0bb400 cu->cuInit(0) failed
[07-06 17:32:43.495]  4208 4242 E ffmpeg:0000:  AVHWDeviceContext @ 0x777d4c0bb400  -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected    
[07-06 17:32:43.495]  4208 4242 E ffmpeg:0000:  AVHWDeviceContext @ 0x777d4c0bb400

[07-06 17:32:43.495]  4208 4242 E codec_util.cpp:0426:  av_hwdevice_ctx_create failed:Generic error in an external library
[07-06 17:32:43.495]  4208 4242 E ffmpeg:0000:  hevc_cuvid @ 0x777d4c32d280 ff_get_format failed: -1

[07-06 17:32:43.495]  4208 4242 E decoder.cpp:0070:  avcodec open failed:Operation not permitted
[07-06 17:32:43.495]  4208 4242 E FFmpegDecoder.cc:0407:  hevc[id:0] hardware decoder detecting finish, not support resolution: 3840x3840 is not supported, failed open: domain:com.insta360.bmg.AVDecoder, code:-1, desc:Operation not permitted(Open Decoder)switch to software decoding
[07-06 17:32:43.497]  4208 4242 E render_exporter2.cc:1317:   renderExport2 notify info 1 domain com.insta360.exporter2 desc
[07-06 17:32:43.548]  4208 4242 E ffmpeg:0000:  AVHWDeviceContext @ 0x777d4ce03140 cu->cuInit(0) failed
[07-06 17:32:43.548]  4208 4242 E ffmpeg:0000:  AVHWDeviceContext @ 0x777d4ce03140  -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected    
[07-06 17:32:43.549]  4208 4242 E ffmpeg:0000:  AVHWDeviceContext @ 0x777d4ce03140

[07-06 17:32:43.549]  4208 4242 E codec_util.cpp:0426:  av_hwdevice_ctx_create failed:Generic error in an external library
[07-06 17:32:43.549]  4208 4242 E ffmpeg:0000:  hevc_cuvid @ 0x777d4cd6f780 ff_get_format failed: -1

[07-06 17:32:43.549]  4208 4242 E decoder.cpp:0070:  avcodec open failed:Operation not permitted
[07-06 17:32:43.549]  4208 4242 E FFmpegDecoder.cc:0407:  hevc[id:2] hardware decoder detecting finish, not support resolution: 3840x3840 is not supported, failed open: domain:com.insta360.bmg.AVDecoder, code:-1, desc:Operation not permitted(Open Decoder)switch to software decoding
[07-06 17:32:43.551]  4208 4242 E render_exporter2.cc:1317:   renderExport2 notify info 1 domain com.insta360.exporter2 desc
[07-06 17:32:44.339]  4208 4242 E render_exporter2.cc:1004:   renderexporter2 color space outside bt709
[07-06 17:32:44.340]  4208 4243 E media_frame_writer.cc:0721:   win videoEncodeOption->cudaContext null
[07-06 17:32:44.341]  4208 4243 E ffmpeg:0000:  h264_nvenc @ 0x777cec002640 Cannot load libnvidia-encode.so.1

[07-06 17:32:44.341]  4208 4243 E ffmpeg:0000:  h264_nvenc @ 0x777cec002640 The minimum required Nvidia driver for nvenc is 470.57.02 or newer     

[07-06 17:32:44.341]  4208 4243 E encoder.cpp:0015:  avcodec open encoder:h264 failed:Operation not permitted
[07-06 17:32:44.341]  4208 4243 E FFmpegEncoder.cc:0333:  err:Operation not permitted
[07-06 17:32:44.341]  4208 4263 E render_exporter2_render.cc:0262:   export render stabilizer null
Cannot load libcudart.so.8.0.61
vulkan runtime init success
process = 1%
```

The progress is stuck on 1% and nothing happens.
The same docker image does work properly with previous versions of SDK.

Am I missing something? Is there an example dockerfile that I can use?
I'd appreciate your help in resolving this.

**Comment by naturehome** [comment]
This issue has been resolved. Please contact the relevant technical support staff to obtain the latest SDK.

**Comment by tomyitav** [comment]
> This issue has been resolved. Please contact the relevant technical support staff to obtain the latest SDK.

We use the firmware in version 1.1.22  - and it still does not work. Is there a newer version of the SDK that should resolve this? @naturehome
